name: "Notify Action"
description: "Notify is a helper utility written in Go that allows you to post output to multiple platforms."
branding:
  icon: "activity"
  color: "blue"

inputs:
  data:
    description: "Input file to send with notify"
    required: true

  config:
    description: "Config file to use with notify"
    required: true

  flags:
    description: "Additional notify CLI flags to use"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/notify ] && GO111MODULE=on go get -v github.com/projectdiscovery/notify/cmd/notify
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        notify -data ${{ inputs.data }} -config ${{ inputs.config }} ${{ inputs.flags }}
      shell: bash
